# https://github.com/cosmtrek/air/blob/master/air_example.toml
root = "."
testdata_dir = "testdata"
tmp_dir = "/tmp"

[build]
args_bin = []
bin = "/tmp/app"
cmd = "go build -o /tmp/app cmd/*.go"
delay = 1500
exclude_dir = ["tmp", "docker", "testdata", "tests"]
exclude_file = []
exclude_regex = ["_test.go"]
exclude_unchanged = false
follow_symlink = false
full_bin = ""
include_dir = ["cmd", "internal", "lib"]
include_ext = ["mod", "go"]
kill_delay = "5s"
log = "/tmp/build-errors.log"
send_interrupt = false
stop_on_error = true

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
time = false

[misc]
clean_on_exit = false

[screen]
clear_on_rebuild = false
